name: NPM Publish

on:
  push:
    branches:
      - experimental
    tags:
      - v*.*.*
      - v*.*.*-*

jobs:
  container-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 7.33.7
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false
      - run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - id: version
        uses: VdustR/semver-action@v0
      - name: version
        env:
          PACKAGE_VERSION: ${{ steps.version.outputs.version }}
        run: npm --no-git-tag-version version "$PACKAGE_VERSION"
      - name: Publish
        env:
          NPM_DIST_TAG: ${{ steps.version.outputs.tag }}
        run: npm publish --tag "$NPM_DIST_TAG" --access public
